name: squid
version: '0.1' 
summary: Squid is a caching proxy for the Web supporting HTTP, HTTPS, FTP, and more.
description: |
  It reduces bandwidth and improves response times by caching 
  and reusing frequently-requested web pages. 
  Squid has extensive access controls and makes a great server accelerator.

grade: stable
confinement: devmode

apps:
  squid:
    command: run-squid.sh start
    stop-command: run-squid.sh stop
    daemon: forking
    plugs: [ home, network, network-bind, network-control, firewall-control, process-control ]

  start:
    command: run-squid.sh start
    plugs: [ home, network, network-bind, network-control, firewall-control, process-control ]

  stop:
    command: run-squid.sh stop
    plugs: [ home, network, network-bind, network-control, firewall-control, process-control ]

  restart:
    command: run-squid.sh restart
    plugs: [ home, network, network-bind, network-control, firewall-control, process-control ]

parts:
  squid:
    plugin: autotools
    source: https://github.com/adglkh/squid-snap-feature.git
    source-type: git
    configflags:
      - --enable-gnuregex
      - --enable-async-io=240 
      - --enable-storeio=ufs,aufs,diskd
      - --enable-poll 
      - --enable-ssl
      - --enable-icmp
      - --enable-kill-parent-hack
      - --enable-cachemgr-hostname=localhost  
      - --enable-linux-netfilter  
      - --enable-large-cache-files
      - --enable-default-hostsfile=/etc/hosts
      - --enable-snmp 
      - --enable-underscore  
      - --enable-arp-acl
      - --enable-snap
      - --with-maxfd=65535
      - --with-openssl=/usr/include/openssl
      - --with-dl
      - --with-pthreads
      - --disable-carp
      - --disable-internal-dns 
      - --disable-ident-lookups 
    build-packages:
      - libssl-dev
      - libxml2-dev
    stage:
      - -etc/squid.conf
    snap:
      - -etc/squid.conf
  squid-customized:
    plugin: copy
    files:
     src/squid/script/*: bin/
     src/squid/conf/*: etc/
